### ISSUE TITLE
App got stuck in splash screen ( Run Distribution ) 

### ISSUE THREAD

**Issue by sachin052** [05nelsonm/kmp-tor#145]
The app is working fine if we run the app directly with help of IDE. But whenever I tried run using Run Distribution it got stuck at splash screen. below is the link of stack trace.
https://pastebin.com/eF8maUef

``23:49:09: Executing task 'runDistributable'...

Executing tasks: [runDistributable] in project C:\Users\Sachin\Documents\sphinx-kotlin-ui\desktop

Configure project :common
Kotlin Multiplatform Projects are an Alpha feature. See: https://kotlinlang.org/docs/reference/evolution/components-stability.html. To hide this message, add 'kotlin.mpp.stability.nowarn=true' to the Gradle properties.

Task :downloadWix SKIPPED
Task :unzipWix UP-TO-DATE
Task :sphinx-kotlin-core:generateCommonMainSphinxDatabaseInterface UP-TO-DATE
Task :sphinx-kotlin-core:generateCommonMainSphinxSettingsDatabaseInterface UP-TO-DATE
Task :sphinx-kotlin-core:compileKotlinJvm UP-TO-DATE
Task :sphinx-kotlin-core:compileJava NO-SOURCE
Task :sphinx-kotlin-core:jvmProcessResources UP-TO-DATE
Task :sphinx-kotlin-core:jvmMainClasses UP-TO-DATE
Task :sphinx-kotlin-core:jvmJar UP-TO-DATE
Task :common:compileKotlinDesktop UP-TO-DATE
Task :common:desktopProcessResources UP-TO-DATE
Task :common:desktopMainClasses UP-TO-DATE
Task :common:desktopJar UP-TO-DATE
Task :desktop:checkRuntime UP-TO-DATE
Task :desktop:createRuntimeImage UP-TO-DATE
Task :desktop:compileKotlinJvm UP-TO-DATE
Task :desktop:compileJava NO-SOURCE
Task :desktop:jvmProcessResources NO-SOURCE
Task :desktop:jvmMainClasses UP-TO-DATE
Task :desktop:jvmJar UP-TO-DATE
Task :desktop:prepareAppResources NO-SOURCE
Task :desktop:createDistributable UP-TO-DATE

Task :desktop:runDistributable
createTorManager: Setting up KmpTor for os: mingw, arch: x64 null
NetworkClientImpl: Listener SocketIOManagerImpl registered null
NetworkClientImpl: Listener NetworkRelayCallImpl registered null
java.lang.ClassNotFoundException: java.lang.management.ManagementFactory
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
at io.matthewnelson.kmp.tor.internal.ProcessId$Companion.get(ProcessId.kt:22)
at io.matthewnelson.kmp.tor.TorConfigProviderJvm.getProcessId(TorConfigProviderJvm.kt:56)
at io.matthewnelson.kmp.tor.manager.TorConfigProvider$retrieve$builder$1.invoke(TorConfigProvider.kt:173)
at io.matthewnelson.kmp.tor.manager.TorConfigProvider$retrieve$builder$1.invoke(TorConfigProvider.kt:136)
at io.matthewnelson.kmp.tor.controller.common.config.TorConfig$Builder$Companion.invoke(TorConfig.kt:293)
at io.matthewnelson.kmp.tor.manager.TorConfigProvider.retrieve$kmp_tor_manager(TorConfigProvider.kt:136)
at io.matthewnelson.kmp.tor.manager.KmpTorLoader$load$validated$1.invokeSuspend(KmpTorLoader.kt:171)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)``

**Comment by 05nelsonm** [comment]
What Java version are you compiling with?

**Comment by sachin052** [comment]
> What Java version are you compiling with?

I've used both 15 and 18

**Comment by 05nelsonm** [comment]
Can you try with Java 11?

**Comment by sachin052** [comment]
> Can you try with Java 11?

Yeah sure will let you know

**Comment by sachin052** [comment]
> Can you try with Java 11?

Packaging native distributions requires JDK runtime version >= 15
Actual version: '11'
Java home: C:\Program Files\Android\Android Studio\jre

**Comment by 05nelsonm** [comment]
Not sure if AndroidStudio's JRE includes that api. Can you try compiling it with OpenJDK?

The `java.lang.ManagementFactory` class is what's throwing the exception which is why I ask. Should be available from Java 11+, so 15 or 18 **should** work.

**Comment by tomastiminskas** [comment]
@05nelsonm we will give you access to the repo so you can take a look to the gradle setup. Thanks in advance

**Comment by 05nelsonm** [comment]
It is definitely a kotlin multiplatform gradle configuration issue with your project.

This library is only available for java and android. Java and Android variants have entirely different instantiation methods, as well as binary file distribution setup and extraction.

Declaring the `kmp-tor` dependency in your `-core` repo module seems to only be providing the `-java` variant when you consume that `-core` module as only has the `jvm` target is expressed in it's setup.

**Comment by 05nelsonm** [comment]
Regarding the `ClassNotFoundException`, I believe it may be caused because your java gradle plugin is not configured to use Java 11+. See https://github.com/05nelsonm/kmp-tor/blob/324c16d2bb9a2feb9c9b861a3cfd06593a223fc5/samples/kotlin/javafx/build.gradle.kts#L37

**Comment by kngako** [comment]
The compose desktop has [documented how to deal with `ClassNotFoundException`](https://github.com/JetBrains/compose-jb/blob/master/tutorials/Native_distributions_and_local_execution/README.md?plain=1#L75-L105) basically had to run the `suggestRuntimeModules` compose desktop gradle task.

This lists all the required modules that the prepackaged application image would need to run in a manner which they can be easily added to the`compose.desktop.application.nativeDistributions.modules` configuration on build.gradle.
