### ISSUE TITLE
Add Onion response parse failure

### ISSUE THREAD

**Issue by 05nelsonm** [05nelsonm/kmp-tor#81]
When adding an existing onion address via it's private key, parsing the controller response fails because the flag `DiscardPK` is not set and it is expecting a private key to be returned.

Controller should use the private key from the request in the returned `HiddenServiceEntry`

```
2022-04-05 07:15:17.721 5208-5208/io.toxicity.push I/System.out: D/TorListener: Action.Controller
2022-04-05 07:15:17.724 5208-5208/io.toxicity.push I/System.out: D/TorListener: >> ADD_ONION ED25519-V3:sGEW/Jjx6F0XrM4WZPsjUNUZrIRxb005HCxFcxN9o1T8ZLOGoLIYXkwAnvWZSIn2qE4s+UA7o9CKvQd8nKLKQA Port=443,127.0.0.1:61267
2022-04-05 07:15:17.826 5208-5208/io.toxicity.push I/System.out: D/TorListener: << 250-ServiceID=3bx4j5cueerin2bhif23vd3ibxol55px544ijgnfbgvj5nb5sytcbdqd
2022-04-05 07:15:17.826 5208-5208/io.toxicity.push I/System.out: D/TorListener: << 250 OK
2022-04-05 07:15:17.879 5208-5208/io.toxicity.push I/System.out: E/TorListener: Failed to add HiddenService for ServerName(value=PushServer)
2022-04-05 07:15:17.879 5208-5208/io.toxicity.push W/System.err: io.matthewnelson.kmp.tor.controller.common.exceptions.TorControllerException: Failed to parse reply for onion address private key
2022-04-05 07:15:17.879 5208-5208/io.toxicity.push W/System.err:     at io.matthewnelson.kmp.tor.controller.RealTorControlProcessor$onionAdd$hsEntry$1.invoke(TorControlProcessor.kt:542)
2022-04-05 07:15:17.879 5208-5208/io.toxicity.push W/System.err:     at io.matthewnelson.kmp.tor.controller.RealTorControlProcessor$onionAdd$hsEntry$1.invoke(TorControlProcessor.kt:510)
2022-04-05 07:15:17.879 5208-5208/io.toxicity.push W/System.err:     at io.matthewnelson.kmp.tor.controller.RealTorController$RealControlPortInteractor$processCommand$2.invokeSuspend(TorController.kt:231)
2022-04-05 07:15:17.879 5208-5208/io.toxicity.push W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-04-05 07:15:17.879 5208-5208/io.toxicity.push W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-04-05 07:15:17.879 5208-5208/io.toxicity.push W/System.err:     at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
2022-04-05 07:15:17.879 5208-5208/io.toxicity.push W/System.err:     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2022-04-05 07:15:17.879 5208-5208/io.toxicity.push W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2022-04-05 07:15:17.880 5208-5208/io.toxicity.push W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-04-05 07:15:17.880 5208-5208/io.toxicity.push W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2022-04-05 07:15:17.881 5208-5208/io.toxicity.push W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by 05nelsonm** [comment]
For the time being, one can simply pass the `TorControlOnionAdd.Flag.DiscardPK` flag in the request and it will return successfully.
